### PR TITLE
Modified parser to recognise a comma delimited lvm format

### PR DESCRIPTION
**Pull request by Professor-0**

### CODE REVIEW

**Comment by Professor-0** [comment]
Sorry, I originally meant to do the PR on my fork. One of my friends who's studying mechanical engineering was given an lvm file to analyse and was directed to this python module to assist. However the module only supported lvm files that were tab delimited and the ones my friend was given were comma delimited. So I rewrote the parser to cope with different Separator headers. It does produce a different signature. The original parser split the data into segments. I couldn't find any examples of an lvm file with multiple data segments so I removed that and just added a singular 'data' key on the output.

**Comment by Professor-0** [comment]
Currently it's just a quick fix to get it working for comma lvms, I will go through the lvm format later and push a more robust version that fits the specification

**Comment by jankoslavic** [comment]
dear @Professor-0, this should be an easy job. The separator is defined in the header. If you provide a short test file, I can try to help.

**Comment by jankoslavic** [comment]
Hi @Professor-0 thank you for your effort. This PR does not look good to me; way too many changes in one PR. You would like to add comma delimiter, is this true? This is not implemented yet, but it should be a few lines of additional code. 
Can you upload please your minimal test file with comma delimiter?

**Comment by Professor-0** [comment]
Hi @jankoslavic I've attached a test file: [pressure_data_min.txt](https://github.com/ladisk/lvm_read/files/15291781/pressure_data_min.txt). I understand if you do not wish to proceed with a specification driven approach. I will close the PR here.

**Comment by jankoslavic** [comment]
Thank you @Professor-0 for the test file. Here is a much simpler implementation:
https://github.com/ladisk/lvm_read/pull/15

Please check it out.

**Pull request closed without merging**
